export default function PostPreviewSection() {
  const examplePost = `I hired 3 wrong people in 6 months.

It nearly killed my startup.

But here's what nobody told me about hiring:

1. Speed kills. Slow down.
2. Culture fit matters more than skills.
3. Trust your gut — it's smarter than your spreadsheet.
4. The best people aren't looking. Go find them.
5. One great hire > three okay ones.

The cost of a bad hire isn't just money.
It's momentum. Morale. Months you can't get back.

Slow down. The right person is worth the wait.

#hiring #startups #leadership`;

  return (
    <section className="bg-gray-50 px-4 py-16">
      <div className="mx-auto max-w-lg">
        <h2 className="text-center text-2xl font-bold text-gray-900">
          See the difference
        </h2>
        <p className="mt-2 text-center text-sm text-gray-600">
          A real post generated by our AI. Not a template — written for a
          specific user&apos;s voice.
        </p>

        <div className="mt-8 rounded-xl border border-gray-200 bg-white shadow-sm">
          <div className="flex items-center gap-3 px-4 pt-4">
            <div className="h-10 w-10 rounded-full bg-blue-100 flex items-center justify-center">
              <span className="text-sm font-bold text-blue-600">A</span>
            </div>
            <div>
              <div className="text-sm font-semibold text-gray-900">
                Alex M.
              </div>
              <div className="text-xs text-gray-500">
                Startup Founder &middot; Just now
              </div>
            </div>
          </div>
          <div className="px-4 py-3">
            <p className="whitespace-pre-line text-sm leading-relaxed text-gray-900">
              {examplePost}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
